<a href="https://colab.research.google.com/github/LatiefDataVisionary/data-quest-challenge-dsi-2025/blob/main/notebooks/awalan_DCM_DMU_2025_Notebook_Cubit_Aku_Dong.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [3]:
val_path = 'https://raw.githubusercontent.com/LatiefDataVisionary/data-quest-challenge-dsi-2025/refs/heads/main/datasets/raw/validation_set.csv'
trai_path = 'https://raw.githubusercontent.com/LatiefDataVisionary/data-quest-challenge-dsi-2025/refs/heads/main/datasets/raw/training_dataset.csv'
df_val = pd.read_csv(val_path)
df_trai = pd.read_csv(trai_path)

In [4]:
df_val.head()

,customer_number,usia,pekerjaan,status_perkawinan,pendidikan,gagal_bayar_sebelumnya,pinjaman_rumah,pinjaman_pribadi,jenis_kontak,bulan_kontak_terakhir,...,jumlah_kontak_kampanye_ini,hari_sejak_kontak_sebelumnya,jumlah_kontak_sebelumnya,hasil_kampanye_sebelumnya,tingkat_variasi_pekerjaan,indeks_harga_konsumen,indeks_kepercayaan_konsumen,suku_bunga_euribor_3bln,jumlah_pekerja,pulau
0,445420,35,penyedia jasa,menikah,SMA,no,yes,yes,cellular,jul,...,1,999,0,nonexistent,1.4,93.918,-42.7,4.960,5228.1,Jawa
1,585604,52,teknisi,lajang,Diploma,unknown,no,no,telephone,may,...,4,999,0,nonexistent,1.1,93.994,-36.4,4.860,5191.0,Papua
2,888824,37,pekerja kasar,menikah,SMP,unknown,yes,no,telephone,may,...,3,999,0,nonexistent,1.1,93.994,-36.4,4.856,5191.0,Bali
3,816820,51,pengangguran,menikah,Diploma,no,no,no,telephone,may,...,3,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,Sumatera
4,542716,45,teknisi,cerai,SMA,no,yes,no,cellular,may,...,1,999,1,failure,-1.8,92.893,-46.2,1.327,5099.1,Sumatera

In [5]:
df_trai.head()

,customer_number,usia,pekerjaan,status_perkawinan,pendidikan,gagal_bayar_sebelumnya,pinjaman_rumah,pinjaman_pribadi,jenis_kontak,bulan_kontak_terakhir,...,hari_sejak_kontak_sebelumnya,jumlah_kontak_sebelumnya,hasil_kampanye_sebelumnya,tingkat_variasi_pekerjaan,indeks_harga_konsumen,indeks_kepercayaan_konsumen,suku_bunga_euribor_3bln,jumlah_pekerja,pulau,berlangganan_deposito
0,531036,63,sosial media specialis,menikah,Pendidikan Tinggi,no,yes,no,cellular,jul,...,999,0,nonexistent,-1.7,94.215,-40.3,0.885,4991.6,Papua,1
1,999241,43,teknisi,menikah,Pendidikan Tinggi,no,yes,no,cellular,nov,...,999,0,nonexistent,-0.1,93.200,-42.0,4.021,5195.8,Sulawesi,0
2,995002,29,sosial media specialis,lajang,Pendidikan Tinggi,no,yes,yes,cellular,jul,...,999,0,nonexistent,1.4,93.918,-42.7,4.958,5228.1,Papua,0
3,932750,40,pekerja kasar,menikah,SMA,no,no,no,telephone,may,...,999,0,nonexistent,1.1,93.994,-36.4,4.859,5191.0,Sumatera,1
4,684699,40,sosial media specialis,lajang,Pendidikan Tinggi,no,no,no,cellular,aug,...,999,0,nonexistent,1.4,93.444,-36.1,4.964,5228.1,Bali,0

In [6]:
df_val.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5729 entries, 0 to 5728
Data columns (total 21 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   customer_number               5729 non-null   int64
 1   usia                          5729 non-null   int64
 2   pekerjaan                     5729 non-null   object
 3   status_perkawinan             5729 non-null   object
 4   pendidikan                    5729 non-null   object
 5   gagal_bayar_sebelumnya        5729 non-null   object
 6   pinjaman_rumah                5729 non-null   object
 7   pinjaman_pribadi              5729 non-null   object
 8   jenis_kontak                  5729 non-null   object
 9   bulan_kontak_terakhir         5729 non-null   object
 10  hari_kontak_terakhir          5729 non-null   object
 11  jumlah_kontak_kampanye_ini    5729 non-null   int64
 12  hari_sejak_kontak_sebelumnya  5729 non-null   int64
 13  jumlah_kontak_sebelumnya      5729 non-null   int64
 14  hasil_kampanye_sebelumnya     5729 non-null   object
 15  tingkat_variasi_pekerjaan     5729 non-null   float64
 16  indeks_harga_konsumen         5729 non-null   float64
 17  indeks_kepercayaan_konsumen   5729 non-null   float64
 18  suku_bunga_euribor_3bln       5729 non-null   float64
 19  jumlah_pekerja                5729 non-null   float64
 20  pulau                         5729 non-null   object
dtypes: float64(5), int64(5), object(11)
memory usage: 940.0+ KB

In [7]:
df_trai.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22916 entries, 0 to 22915
Data columns (total 22 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   customer_number               22916 non-null  int64
 1   usia                          22916 non-null  int64
 2   pekerjaan                     22916 non-null  object
 3   status_perkawinan             22916 non-null  object
 4   pendidikan                    22916 non-null  object
 5   gagal_bayar_sebelumnya        22916 non-null  object
 6   pinjaman_rumah                22916 non-null  object
 7   pinjaman_pribadi              22916 non-null  object
 8   jenis_kontak                  22916 non-null  object
 9   bulan_kontak_terakhir         22916 non-null  object
 10  hari_kontak_terakhir          22916 non-null  object
 11  jumlah_kontak_kampanye_ini    22916 non-null  int64
 12  hari_sejak_kontak_sebelumnya  22916 non-null  int64
 13  jumlah_kontak_sebelumnya      22916 non-null  int64
 14  hasil_kampanye_sebelumnya     22916 non-null  object
 15  tingkat_variasi_pekerjaan     22916 non-null  float64
 16  indeks_harga_konsumen         22916 non-null  float64
 17  indeks_kepercayaan_konsumen   22916 non-null  float64
 18  suku_bunga_euribor_3bln       22916 non-null  float64
 19  jumlah_pekerja                22916 non-null  float64
 20  pulau                         22916 non-null  object
 21  berlangganan_deposito         22916 non-null  int64
dtypes: float64(5), int64(6), object(11)
memory usage: 3.8+ MB

In [8]:
df_val.describe()

,customer_number,usia,jumlah_kontak_kampanye_ini,hari_sejak_kontak_sebelumnya,jumlah_kontak_sebelumnya,tingkat_variasi_pekerjaan,indeks_harga_konsumen,indeks_kepercayaan_konsumen,suku_bunga_euribor_3bln,jumlah_pekerja
count,5729.000000,5729.000000,5729.000000,5729.000000,5729.000000,5729.000000,5729.000000,5729.000000,5729.000000,5729.000000
mean,548493.630826,39.852679,2.545470,964.329377,0.162157,0.096003,93.571413,-40.471356,3.638297,5167.914662
std,258992.541542,10.348971,2.618704,182.310129,0.471306,1.565580,0.576929,4.632091,1.727321,71.802171
min,100423.000000,18.000000,1.000000,0.000000,0.000000,-3.400000,92.201000,-50.800000,0.634000,4963.600000
25%,323527.000000,32.000000,1.000000,999.000000,0.000000,-1.800000,93.075000,-42.700000,1.344000,5099.100000
50%,552893.000000,38.000000,2.000000,999.000000,0.000000,1.100000,93.444000,-41.800000,4.857000,5191.000000
75%,772131.000000,46.000000,3.000000,999.000000,0.000000,1.400000,93.994000,-36.400000,4.961000,5228.100000
max,999897.000000,98.000000,43.000000,999.000000,5.000000,1.400000,94.767000,-26.900000,5.045000,5228.100000

In [11]:
df_trai.describe()

,customer_number,usia,jumlah_kontak_kampanye_ini,hari_sejak_kontak_sebelumnya,jumlah_kontak_sebelumnya,tingkat_variasi_pekerjaan,indeks_harga_konsumen,indeks_kepercayaan_konsumen,suku_bunga_euribor_3bln,jumlah_pekerja,berlangganan_deposito
count,22916.000000,22916.000000,22916.000000,22916.000000,22916.000000,22916.000000,22916.000000,22916.000000,22916.000000,22916.000000,22916.000000
mean,550930.993193,40.016233,2.561878,962.210377,0.170143,0.077915,93.576541,-40.485717,3.617890,5166.773124,0.114069
std,259909.889175,10.438059,2.794178,187.566774,0.490611,1.576176,0.580586,4.641091,1.737591,72.479698,0.317902
min,100108.000000,17.000000,1.000000,0.000000,0.000000,-3.400000,92.201000,-50.800000,0.634000,4963.600000,0.000000
25%,325755.000000,32.000000,1.000000,999.000000,0.000000,-1.800000,93.075000,-42.700000,1.344000,5099.100000,0.000000
50%,553139.000000,38.000000,2.000000,999.000000,0.000000,1.100000,93.876000,-41.800000,4.857000,5191.000000,0.000000
75%,777157.500000,47.000000,3.000000,999.000000,0.000000,1.400000,93.994000,-36.400000,4.961000,5228.100000,0.000000
max,999997.000000,98.000000,42.000000,999.000000,7.000000,1.400000,94.767000,-26.900000,5.045000,5228.100000,1.000000

In [12]:
for col in df_trai.columns:
  if df_trai[col].dtype == 'object' or df_trai[col].dtype.name == 'category':
    print(f"Kolom '{col}': {df_trai[col].unique().tolist()}")

Kolom 'pekerjaan': ['sosial media specialis', 'teknisi', 'pekerja kasar', 'manajer', 'asisten rumah tangga', 'mahasiswa', 'penyedia jasa', 'pemilik bisnis', 'entrepreneur', 'pengangguran', 'pensiunan', 'unknown']
Kolom 'status_perkawinan': ['menikah', 'lajang', 'cerai', 'unknown']
Kolom 'pendidikan': ['Pendidikan Tinggi', 'SMA', 'Tidak Tamat SD', 'SMP', 'Diploma', 'SD', 'unknown', 'TIDAK SEKOLAH']
Kolom 'gagal_bayar_sebelumnya': ['no', 'unknown', 'yes']
Kolom 'pinjaman_rumah': ['yes', 'no', 'unknown']
Kolom 'pinjaman_pribadi': ['no', 'yes', 'unknown']
Kolom 'jenis_kontak': ['cellular', 'telephone']
Kolom 'bulan_kontak_terakhir': ['jul', 'nov', 'may', 'aug', 'oct', 'apr', 'jun', 'sep', 'mar', 'dec']
Kolom 'hari_kontak_terakhir': ['fri', 'thu', 'wed', 'tue', 'mon']
Kolom 'hasil_kampanye_sebelumnya': ['nonexistent', 'failure', 'success']
Kolom 'pulau': ['Papua', 'Sulawesi', 'Sumatera', 'Bali', 'NTT', 'Jawa', 'NTB', 'Kalimantan']

In [13]:
for col in df_val.columns:
  if df_val[col].dtype == 'object' or df_val[col].dtype.name == 'category':
    print(f"Kolom '{col}': {df_val[col].unique().tolist()}")

Kolom 'pekerjaan': ['penyedia jasa', 'teknisi', 'pekerja kasar', 'pengangguran', 'sosial media specialis', 'pensiunan', 'asisten rumah tangga', 'manajer', 'mahasiswa', 'entrepreneur', 'pemilik bisnis', 'unknown']
Kolom 'status_perkawinan': ['menikah', 'lajang', 'cerai', 'unknown']
Kolom 'pendidikan': ['SMA', 'Diploma', 'SMP', 'Tidak Tamat SD', 'SD', 'Pendidikan Tinggi', 'unknown', 'TIDAK SEKOLAH']
Kolom 'gagal_bayar_sebelumnya': ['no', 'unknown']
Kolom 'pinjaman_rumah': ['yes', 'no', 'unknown']
Kolom 'pinjaman_pribadi': ['yes', 'no', 'unknown']
Kolom 'jenis_kontak': ['cellular', 'telephone']
Kolom 'bulan_kontak_terakhir': ['jul', 'may', 'jun', 'apr', 'nov', 'aug', 'mar', 'dec', 'sep', 'oct']
Kolom 'hari_kontak_terakhir': ['mon', 'thu', 'wed', 'tue', 'fri']
Kolom 'hasil_kampanye_sebelumnya': ['nonexistent', 'failure', 'success']
Kolom 'pulau': ['Jawa', 'Papua', 'Bali', 'Sumatera', 'Kalimantan', 'NTB', 'NTT', 'Sulawesi']